### ISSUE TITLE
Error response from daemon: manifest for gcr.io/camunda-researchanddevelopment/zeebe-operate-helm:0.0.42 not found: manifest unknown: Failed to fetch "0.0.42" from request "/v2/camunda-researchanddevelopment/zeebe-operate-helm/manifests/0.0.42".

### ISSUE THREAD

**Issue by BigeYoung** [zeebe-io/zeebe-full-helm#102]
It seems that [gcr.io/camunda-researchanddevelopment/zeebe-operate-helm](https://console.cloud.google.com/gcr/images/camunda-researchanddevelopment/GLOBAL/zeebe-operate-helm) is empty.

**Comment by BigeYoung** [comment]
![image](https://user-images.githubusercontent.com/20485391/110568731-713b8f80-818e-11eb-96bc-eebeaf974dbd.png)

**Comment by salaboy** [comment]
Yes, this is a duplicate of https://github.com/zeebe-io/zeebe-cluster-helm/issues/107
I am working on it.. can you please use a previous version of the chart? You can find all the available version here: HTTP://github.com/zeebe-io/zeebe-helm

**Comment by BigeYoung** [comment]
Okay, thank you very much. I have downgraded through `helm install --version`.
