### ISSUE TITLE
Cannot pull image "gcr.io/camunda-researchanddevelopment/zeebe-cluster-helm:0.0.211"

### ISSUE THREAD

**Issue by Sargastico** [zeebe-io/zeebe-full-helm#103]
I was trying to deploy zeebe on GKE with the new helm chart release `zeebe-full-helm-0.0.133`, but GKE was not able to pull the image from: `gcr.io/camunda-researchanddevelopment/zeebe-cluster-helm:0.0.211`, causing a  `ImagePullBackOff`.

I browsed into `gcr.io/camunda-researchanddevelopment`, but did not find the `zeebe-cluster-helm` or any image related.

I was also unable to pull the image locally using docker. The docker output:

`Error response from daemon: manifest for gcr.io/camunda-researchanddevelopment/zeebe-cluster-helm:0.0.211 not found: manifest unknown: Failed to fetch "0.0.211" from request "/v2/camunda-researchanddevelopment/zeebe-cluster-helm/manifests/0.0.211".`

I don't know if this is a problem with the gcr.io or with the helm chart, so I'm reporting it.

**Comment by salaboy** [comment]
I am working on fixing that issue if you use a previous version with --version you can get it working until I fix latest. There is an issue already reporting this issue

**Comment by salaboy** [comment]
solved in full 0.0.134
