### ISSUE TITLE
zeeqs pod crashing after http graphql request.

### ISSUE THREAD

**Issue by Sargastico** [zeebe-io/zeebe-full-helm#104]
- Running on GKE
- Deploy command: `helm install zeebe ./zeebe-full-helm -f ./zeebe-full-helm/values.yaml -n zeebe`
- I enabled zeeqs and tasklist on values.yaml

I did a port fowarding from the zeeqs service running on port 9000 to my local machine, but when I sent a request  (POST query or /graphiql), the zeeqs pod crashes with a  `Error with exit code 1` and restart.

Following the logs I found a [error stacktrace](https://pastebin.com/d11RbXAe).

**Comment by Sargastico** [comment]
I also finded other log entries that might be helpful to identify the problem:

`hz.client_1 [dev] [4.1.1] Exception during initial connection to [localhost]:5701: com.hazelcast.core.HazelcastException: java.net.SocketException: Connection refused to address localhost/127.0.0.1:5701`

it looks like the application is trying to connect to hazelcast on localhost. The service endpoint may not be resolved correctly.

**Comment by salaboy** [comment]
@Sargastico yes those are community charts so we might need some help to get them working as they should. It looks like a configuration is missing to point ZeeQS to the Zeebe Broker which has hazelcast enabled.

**Comment by salaboy** [comment]
@Sargastico have you looked at this: https://github.com/zeebe-io/zeebe-helm-profiles/blob/master/zeebe-dev-with-zeeqs-profile.yaml ?

**Comment by Sargastico** [comment]
@salaboy I tried this profile with helm, but the zeeqs still points to localhost and not to the hazelcast service.

I also tried to manually insert the env variable (hard coding it, replacing the helm resolver code) inside the `zeebe-full-helm/charts/zeebe-zeeqs-helm/templates/deployment.yaml` called `ZEEBE_HAZELCAST_CONNECTION`, but it had no effect.

Maybe the environment variables are not overriding the default address (localhost) of hazelcast on zeeqs.

**Comment by salaboy** [comment]
@Sargastico yes.. that might be the case.. can you look into the container.. maybe the env variable has changed.. 
Looking at the zeeqs repo.. I think that variable has changed to: 
`ZEEBE_CLIENT_WORKER_HAZELCAST_CONNECTION` can you give that a try? 

https://github.com/zeebe-io/zeeqs/blob/master/app/src/main/resources/application.yml#L8

**Comment by salaboy** [comment]
remember that you can always do a kubectl edit deploy to change that in the cluster.. and if that works then we can send a PR to the Chart

**Comment by Sargastico** [comment]
@salaboy It's working! Changing the name of the env variable to `ZEEBE_CLIENT_WORKER_HAZELCAST_CONNECTION` fix the issue.

I sent the PR.

**Comment by salaboy** [comment]
@Sargastico awesome!!! glad to hear that helped!
