### ISSUE TITLE
ZeeQs dependency is outdated and incompatible with Zeebe 1.x

### ISSUE THREAD

**Issue by falko** [zeebe-io/zeebe-full-helm#111]
Depends on https://github.com/camunda-community-hub/zeeqs/issues/153 and https://github.com/camunda-community-hub/zeebe-zeeqs-helm/pull/7

**Comment by falko** [comment]
The PR on the ZeeQs helm chart is ready for review: camunda-community-hub/zeebe-zeeqs-helm#7

**Comment by ChrisKujawa** [comment]
done
