### ISSUE TITLE
Storage Class Not Found on Deployment

### ISSUE THREAD

**Issue by mdiloreto16** [zeebe-io/zeebe-full-helm#22]
Hey, I'm not 100% sure if this is the right place to ask this, however I'm currently trying to get this chart deployed on a dev cluster. Basically after doing a helm install for zeebe/zeebe-full, the PVC's are stuck in pending state with this: 

no persistent volumes available for this claim and no storage class is set.

I think the issues is that the deployment is attempting to use the default storage class, however on this cluster it is a different storage class. I'm wondering if there is a flag I can pass in during the helm install --name=<name> zeebe/zeebe-full that will allow me to specify which storage class to use.

**Comment by salaboy** [comment]
@mdiloreto16 hi there, this is kinda the right place. Thanks for your question.. but as you mention it is a more generic kubernetes question. This in some way was solved for kubernetes kind and docker for Mac. If you look at the docs.zeebe.io in the kubernetes section there is a values.yaml file for kind that is doing exactly what you need

**Comment by mdiloreto16** [comment]
Thanks for the quick reply! I think part of my issue now is around my access level on our development environment. Seems like the file you mentioned is able to accomplish what I'm looking for.
