### ISSUE TITLE
helm install zeebe/zeebe-full --version 0.0.74 is returning an error

### ISSUE THREAD

**Issue by evanniedojadlo** [zeebe-io/zeebe-full-helm#68]
Using _helm install zeebe-cluster-production zeebe/zeebe-full --version 0.0.74_ is returning the following error:                                                                                 

_Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: unknown object type "nil" in ConfigMap.data.application.yaml_

Environment context:
This is a fresh helm install on a GKE cluster with nodes running Kubernetes 1.15

**Comment by salaboy** [comment]
@evanniedojadlo thanks for reporting.. I will be fixing this soon.

**Comment by salaboy** [comment]
@evanniedojadlo this should be fixed now.. thanks again for reporting.. you will need to do a `helm repo update` to fetch the latest charts.

**Comment by evanniedojadlo** [comment]
@salaboy thank you, I tested this and it works without issue now.

**Comment by salaboy** [comment]
@evanniedojadlo great!
